name: Testar variáveis

on:
  workflow_dispatch:

jobs:
  test-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print variáveis sensíveis (com segurança)
        run: |
          echo "TOKEN_API (inicio): ${TOKEN_API:0:5}..."
          echo "TOKEN_API (tamanho): ${#TOKEN_API}"
          echo "CLIENT_ID: ${CLIENT_ID}"
          echo "SENDER_EMAIL: ${SENDER_EMAIL}"
        env:
          TOKEN_API: ${{ vars.TOKEN_API }}
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          SENDER_EMAIL: ${{ vars.SENDER_EMAIL }}
