name: Testar variáveis

on:
  workflow_dispatch:

jobs:
  debug-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Testar variáveis do ambiente
        run: |
          echo "TOKEN_API: ${TOKEN_API:0:5}... (len=${#TOKEN_API})"
          echo "CLIENT_ID: ${CLIENT_ID:0:5}... (len=${#CLIENT_ID})"
          echo "DATABASE_URL: ${DATABASE_URL:0:5}... (len=${#DATABASE_URL})"
        env:
          TOKEN_API: ${{ vars.TOKEN_API }}
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          DATABASE_URL: ${{ vars.DATABASE_URL }}